---

- name: Install Red Hat Access Insights Client
  yum: name={{ item }} state=present
  with_items:
      - redhat-access-insights

- name: Configure Red Hat Access Insights Client
  template: src=insights-client.conf.j2 dest=/etc/redhat-access-insights/redhat-access-insights.conf

- stat: path=/etc/redhat-access-insights/.unregistered
  register: unreg

# Only register if this system hasn't been registered before
- name: Register to the Red Hat Access Insights Service
  command: redhat-access-insights --register creates=/etc/redhat-access-insights/.registered
  when: unreg.stat.exists == false
